#define which types should be removed, options:
#   rideable  - removes only rideable minecarts (default)
#   furnace   - removes furnace minecarts
#   storage   - removes storage minecarts
#   hopper    - removes hopper minecarts
#   explosive - removes explosive minecarts
#   spawner   - removes spawner minecarts
#   all       - removes every minecart
#If you want to specifiy more options, use ',' operand like so: rideable,explosive,spawner
remove: regular

#true - ONLY empty carts will be removed (default)
#false - removes also occupied and/or filled minecarts (if specified above)
empty_only: true