main: name.brychta.minecartremover.MinecartRemover
name: MinecartRemover
version: 0.1
author: Martin Brychta aka SirPole, [CZE]
commands:
    rmmc:
        description: Removes empty, useless minecarts.
        usage: "/<command> range"