main: name.brychta.minecartremover.MinecartRemover
name: MinecartRemover
version: 0.3
author: Martin Brychta aka SirPole, [CZE]
commands:
    rmmc:
        description: Removes empty, useless(Now ANY) minecarts.
permissions:
    minecraftremover.rmmc:
        description: Gives access to /rmmc command
        default: op